language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
gemfile:
  - gemfiles/Gemfile.rspec2-x
  - gemfiles/Gemfile.rspec3-0
  - gemfiles/Gemfile.rspec3-1
  - gemfiles/Gemfile.rspec3-2
  - gemfiles/Gemfile.rspec3-3
  - gemfiles/Gemfile.rspec3-4
  - gemfiles/Gemfile.rspec3-5
script: bundle exec rspec
