language: ruby
cache: bundler
rvm:
  - 3.1
  - 3.0
  - 2.7
  - 2.6
before_install:
  - gem install bundler -v $(grep -F "BUNDLED WITH" -A 1 "${BUNDLE_GEMFILE:-Gemfile}.lock" | tail -1)
gemfile:
  - gemfiles/rspec_2_x.gemfile
  - gemfiles/rspec_3_0.gemfile
  - gemfiles/rspec_3_1.gemfile
  - gemfiles/rspec_3_2.gemfile
  - gemfiles/rspec_3_3.gemfile
  - gemfiles/rspec_3_4.gemfile
  - gemfiles/rspec_3_5.gemfile
  - gemfiles/rspec_3_6.gemfile
  - gemfiles/rspec_3_7.gemfile
  - gemfiles/rspec_3_8.gemfile
  - gemfiles/rspec_3_9.gemfile
  - gemfiles/rspec_3_10.gemfile
script: bundle exec rspec
