language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
gemfile:
  - gemfiles/rspec_2_x.gemfile
  - gemfiles/rspec_3_0.gemfile
  - gemfiles/rspec_3_1.gemfile
  - gemfiles/rspec_3_2.gemfile
  - gemfiles/rspec_3_3.gemfile
  - gemfiles/rspec_3_4.gemfile
  - gemfiles/rspec_3_5.gemfile
  - gemfiles/rspec_3_6.gemfile
  - gemfiles/rspec_3_7.gemfile
script: bundle exec rspec
